# Change these first
owner: FhenixProtocol # Your GitHub organization or username, where this repository lives
repo: fhenix-status # The name of this repository

sites:
  - name: Testnet API Endpoint
    url: $TESTNET_ENDPOINT
    icon: https://www.fhenix.io/wp-content/uploads/2023/09/cropped-Favicon_Dark-32x32.png
  - name: Fhenix Explorer
    url: https://explorer.helium.fhenix.zone/api/v2/config/backend-version
  - name: Fhenix Docs
    url: https://docs.fhenix.zone
  - name: Faucet
    url: https://get-helium.fhenix.zone
  - name: Landing Page
    url: https://www.fhenix.io

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.fhenix.zone
  # baseUrl: /fhenix-status
  faviconSvg: https://raw.githubusercontent.com/FhenixProtocol/fhenix-status/master/assets/Favicon_Dark.svg
  logoUrl: https://raw.githubusercontent.com/FhenixProtocol/fhenix-status/master/assets/Fhenix.svg
  name: ""
  theme: dark
  introTitle: "Status page monitoring the uptime of all Fhenix Testnet Services."
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
